- server/db/models/index.js
- server/db/models/picture.js
- server/db/models/team.js
- server/db/models/user.js
3 models (2 commented out) 
Associations
> userTeamPicModsAssoc

- App.js
- client/components/CluePage.js
- package-lock.json
- package.json
> initial clue page

- package-lock.json
> added package-lock.json back in

- client/components/index.js
- package-lock.json
- package.json
- server/api/images.js
- server/api/index.js
- server/clarifai/compare.js
- server/clarifai/index.js
- server/index.js
> api route for comparing images

- package-lock.json
> packagelock fixed

- client/components/Camera.js
- client/components/Gps.js
- client/ngrok.js
- server/api/images.js
- server/db/models/index.js
- server/db/models/picture.js
> Image technology integration

- App.js
- client/components/CluePage.js
- client/components/GamesPage.js
- client/components/HomePage.js
- client/components/NavBar.js
- client/components/index.js
> page-switching

- .gitignore
- client/ngrok.js
- server/api/images.js
- server/clarifai/compare.js
> Attach clarifai

- .gitignore
- client/ngrok.js
- script/seed.js
- server/db/models/clue.js
- server/db/models/index.js
> seed debugged

- .gitignore
- App.js
- client/components/HomePage.js
- client/components/SignUp.js
- client/ngrok.js
- client/store/index.js
- client/store/user.js
- package-lock.json
- package.json
- server/api/images.js
- server/api/index.js
- server/api/users.js
- server/db/models/index.js
> redux store up and running, and signup component adding new user to db

- package-lock.json
- package.json
> added nodemon and a script, start with npm run server

- client/ngrok.js
- client/store/games.js
- client/store/index.js
- package.json
- screens/GamesPage.js
- server/api/game.js
> added better games page and attached to database

- App.js
- client/components/Camera.js
- client/components/GameOver.js
- client/components/SignUp.js
- client/components/index.js
- client/ngrok.js
- server/api/images.js
> basic wireframe of Game Over page built out

- .editorconfig
- .eslintrc.json
- .prettierignore
- .prettierrc.yml
- .travis.yml
- client/components/Camera.js
- client/components/Login.js
- client/components/SignUp.js
- client/ngrok.js
- client/store/games.js
- client/store/user.js
- package-lock.json
- package.json
- screens/Camera.js
- screens/GamesPage.js
- server/api/images.js
- server/clarifai/compare.js
> User profile

- client/components/Camera.js
- client/components/MakeClueCamera.js
- screens/Camera.js
- screens/CluePage.js
- server/api/game.js
- server/clarifai/compare.js
> clarifai works

- client/components/MakeClueCamera.js
- client/components/MakeGame.js
- client/ngrok.js
- client/routes/tab.js
- client/screens/Camera.js
- client/screens/GameOver.js
- client/screens/GamesPage.js
- client/screens/Scene.js
Reverts MERV-spice/basic-merv#47
> Revert "Auto nav"

- client/ngrok.js
- client/screens/GamesPage.js
> removed two syntax errors in gamespage

- client/components/MakeClueCamera.js
- client/components/MakeGame.js
- client/screens/GamesPage.js
- server/api/game.js
> added styling to makegame and makecluecamera

- client/components/MakeGame.js
- client/screens/CluePage.js
- client/screens/GamesPage.js
- server/api/game.js
> Count down timer2

- client/components/GameOver.js
- client/ngrok.js
- client/screens/CluePage.js
> changes for gameover glitch

- client/components/Login.js
- client/ngrok.js
- client/store/user.js
> auto login and login page is within nav component

- client/ngrok.js
- client/store/user.js
removed a . for importing request
> fixed import

- client/components/MakeGame.js
> added a remove clue button to make game

- client/components/MakeGame.js
- client/screens/GamesPage.js
- client/store/user.js
> added some refreshing

- client/components/MakeGame.js
- client/ngrok.js
- client/screens/GamesPage.js
> overlay shows when game is successfully made

- server/api/game.js
> games sorted, only games still valid are rendering on all games

- client/screens/CluePage.js
- script/seed.js
- server/api/game.js
- server/notifications/notification.js
> Moreeslintfix

- client/screens/CluePage.js
> overlayfixed

- client/components/MakeGame.js
> time limitations added

- client/components/Camera.js
- client/components/Route.js
- client/ngrok.js
- client/screens/Camera.js
- client/screens/FriendsPage.js
- client/store/user.js
> styled friends page

- client/screens/FriendsPage.js
> changed styling

- client/components/MakeClueCamera.js
- client/components/MakeGame.js
- client/ngrok.js
- client/screens/GamesPage.js
> makegame overlay working'

- client/components/MakeGame.js
- client/ngrok.js
> delete button fixed and order of render fixed

- client/components/GameOver.js
- client/ngrok.js
- client/routes/tab.js
- client/screens/CluePage.js
partially fixed the hint bug but only if they click the game over button, not if they navigate to a new game through the tabnav. Changed color of headers to be less white
> Camerahead
